name: my test workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome kk funda messgae
          run: echo "Hello KK FUNDA WELCOME TO GA"
        - name: list the files
          run: ls
        - name: print the present working dir
          run: pwd